// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tafseel.Infrastructure.Persistence;

#nullable disable

namespace Tafseel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TafseelDbContext))]
    [Migration("20260726154535_Phase4TeacherMarketplace")]
    partial class Phase4TeacherMarketplace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tafseel.Domain.Catalog.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.FavoriteTeacher", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeacherId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("StudentId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("FavoriteTeachers");
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherAvailabilityException", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId", "StartsAt", "EndsAt");

                    b.ToTable("TeacherAvailabilityExceptions", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherAvailabilityExceptions_Range", "[EndsAt] > [StartsAt]");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherAvailabilityRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time");

                    b.Property<int?>("SlotMinutes")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId", "DayOfWeek", "Start", "End")
                        .IsUnique();

                    b.ToTable("TeacherAvailabilityRules", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherAvailabilityRules_Day", "[DayOfWeek] BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_TeacherAvailabilityRules_Slot", "[SlotMinutes] IS NULL OR [SlotMinutes] BETWEEN 15 AND 240");

                            t.HasCheckConstraint("CK_TeacherAvailabilityRules_Time", "[End] > [Start]");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateOnly?>("From")
                        .HasColumnType("date");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("To")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherCredential", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherCredential_DateRange", "[To] IS NULL OR [From] IS NULL OR [To] >= [From]");
                        });

                    b.HasDiscriminator<string>("CredentialType").HasValue("TeacherCredential");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherEducationLevel", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EducationLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeacherId", "EducationLevelId");

                    b.HasIndex("EducationLevelId");

                    b.ToTable("TeacherEducationLevels");
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherLanguage", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeacherId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("TeacherLanguages");
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherProfile", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CompletedOrders")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<int>("ResponseTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TeacherId");

                    b.HasIndex("IsPublished", "AverageRating");

                    b.ToTable("TeacherProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherProfiles_Counts", "[RatingCount] >= 0 AND [CompletedOrders] >= 0");

                            t.HasCheckConstraint("CK_TeacherProfiles_Rating", "[AverageRating] BETWEEN 0 AND 5");

                            t.HasCheckConstraint("CK_TeacherProfiles_ResponseTime", "[ResponseTimeMinutes] BETWEEN 0 AND 43200");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<int>("DeliveryHours")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Revisions")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("ServiceCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCatalogItemId");

                    b.HasIndex("TeacherId", "IsActive");

                    b.HasIndex("SubjectId", "ServiceCatalogItemId", "IsActive", "Price");

                    b.ToTable("TeacherServices", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherServices_Currency", "[Currency] LIKE '___' AND [Currency] NOT LIKE '____%'");

                            t.HasCheckConstraint("CK_TeacherServices_DeliveryHours", "[DeliveryHours] BETWEEN 1 AND 8760");

                            t.HasCheckConstraint("CK_TeacherServices_Price", "[Price] > 0");

                            t.HasCheckConstraint("CK_TeacherServices_Revisions", "[Revisions] BETWEEN 0 AND 20");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherTeachingSample", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TopicId");

                    b.HasIndex("TeacherId", "PublishedAt");

                    b.ToTable("TeacherTeachingSamples", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherTeachingSamples_Duration", "[DurationSeconds] BETWEEN 1 AND 3600");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherTopic", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeacherId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("TeacherTopics");
                });

            modelBuilder.Entity("Tafseel.Domain.TeacherApplications.TeacherApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedReviewerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("DemoDurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("DemoStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("QualificationTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("QualificationTopicId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId", "SubjectId")
                        .IsUnique()
                        .HasFilter("[Status] IN (0, 1, 2, 3)");

                    b.ToTable("TeacherApplications", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherApplications_DemoDurationSeconds", "[DemoDurationSeconds] IS NULL OR [DemoDurationSeconds] BETWEEN 1 AND 600");

                            t.HasCheckConstraint("CK_TeacherApplications_ExperienceYears", "[ExperienceYears] BETWEEN 0 AND 80");

                            t.HasCheckConstraint("CK_TeacherApplications_Priority", "[Priority] BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_TeacherApplications_Status", "[Status] BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.TeacherApplications.TeacherApplicationReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TeacherApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeacherApplicationId");

                    b.ToTable("TeacherApplicationReview", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherApplicationReview_Decision", "[Decision] BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.TeacherApplications.TeacherApplicationStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NextStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeacherApplicationId");

                    b.ToTable("TeacherApplicationStatusHistory", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherApplicationStatusHistory_NextStatus", "[NextStatus] BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_TeacherApplicationStatusHistory_PreviousStatus", "[PreviousStatus] IS NULL OR [PreviousStatus] BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_TeacherApplicationStatusHistory_Transition", "[PreviousStatus] IS NULL OR [PreviousStatus] <> [NextStatus]");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.TeacherApplications.TeacherEvaluationScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Criterion")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherApplicationReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeacherApplicationReviewId", "Criterion")
                        .IsUnique();

                    b.ToTable("TeacherEvaluationScore", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherEvaluationScore_Criterion", "[Criterion] BETWEEN 0 AND 8");

                            t.HasCheckConstraint("CK_TeacherEvaluationScore_Score", "[Score] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.TeacherApplications.TeacherSubjectQualification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId", "SubjectId")
                        .IsUnique();

                    b.ToTable("TeacherSubjectQualifications");
                });

            modelBuilder.Entity("Tafseel.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("EmailConfirmationSentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Tafseel.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "FamilyId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Tafseel.Domain.Catalog.EducationLevel", b =>
                {
                    b.HasBaseType("Tafseel.Domain.Catalog.CatalogItem");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("EducationLevels", t =>
                        {
                            t.HasCheckConstraint("CK_EducationLevel_NormalizedName", "[NormalizedName] <> ''");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.Catalog.QualificationTopic", b =>
                {
                    b.HasBaseType("Tafseel.Domain.Catalog.CatalogItem");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("MaxVideoSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("SubjectId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("[SubjectId] IS NOT NULL");

                    b.ToTable("QualificationTopics", t =>
                        {
                            t.HasCheckConstraint("CK_QualificationTopic_NormalizedName", "[NormalizedName] <> ''");

                            t.HasCheckConstraint("CK_QualificationTopics_MaxVideoSeconds", "[MaxVideoSeconds] BETWEEN 30 AND 600");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.Catalog.ServiceCatalogItem", b =>
                {
                    b.HasBaseType("Tafseel.Domain.Catalog.CatalogItem");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("ServiceCatalogItems", t =>
                        {
                            t.HasCheckConstraint("CK_ServiceCatalogItem_NormalizedName", "[NormalizedName] <> ''");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.Catalog.Subject", b =>
                {
                    b.HasBaseType("Tafseel.Domain.Catalog.CatalogItem");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Subjects", t =>
                        {
                            t.HasCheckConstraint("CK_Subject_NormalizedName", "[NormalizedName] <> ''");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.Catalog.TeachingLanguage", b =>
                {
                    b.HasBaseType("Tafseel.Domain.Catalog.CatalogItem");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("TeachingLanguages", t =>
                        {
                            t.HasCheckConstraint("CK_TeachingLanguage_NormalizedName", "[NormalizedName] <> ''");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.Catalog.Topic", b =>
                {
                    b.HasBaseType("Tafseel.Domain.Catalog.CatalogItem");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("SubjectId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("[SubjectId] IS NOT NULL");

                    b.ToTable("Topics", t =>
                        {
                            t.HasCheckConstraint("CK_Topic_NormalizedName", "[NormalizedName] <> ''");
                        });
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherCertification", b =>
                {
                    b.HasBaseType("Tafseel.Domain.Marketplace.TeacherCredential");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_TeacherCredential_DateRange", "[To] IS NULL OR [From] IS NULL OR [To] >= [From]");
                        });

                    b.HasDiscriminator().HasValue("Certification");
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherExperience", b =>
                {
                    b.HasBaseType("Tafseel.Domain.Marketplace.TeacherCredential");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_TeacherCredential_DateRange", "[To] IS NULL OR [From] IS NULL OR [To] >= [From]");
                        });

                    b.HasDiscriminator().HasValue("Experience");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.FavoriteTeacher", b =>
                {
                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherAvailabilityException", b =>
                {
                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherAvailabilityRule", b =>
                {
                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherCredential", b =>
                {
                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherEducationLevel", b =>
                {
                    b.HasOne("Tafseel.Domain.Catalog.EducationLevel", null)
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherLanguage", b =>
                {
                    b.HasOne("Tafseel.Domain.Catalog.TeachingLanguage", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherProfile", b =>
                {
                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Tafseel.Domain.Marketplace.TeacherProfile", "TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherService", b =>
                {
                    b.HasOne("Tafseel.Domain.Catalog.ServiceCatalogItem", null)
                        .WithMany()
                        .HasForeignKey("ServiceCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tafseel.Domain.Catalog.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherTeachingSample", b =>
                {
                    b.HasOne("Tafseel.Domain.Catalog.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tafseel.Domain.Catalog.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Tafseel.Domain.Marketplace.TeacherTopic", b =>
                {
                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tafseel.Domain.Catalog.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.TeacherApplications.TeacherApplication", b =>
                {
                    b.HasOne("Tafseel.Domain.Catalog.QualificationTopic", null)
                        .WithMany()
                        .HasForeignKey("QualificationTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tafseel.Domain.Catalog.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.TeacherApplications.TeacherApplicationReview", b =>
                {
                    b.HasOne("Tafseel.Domain.TeacherApplications.TeacherApplication", null)
                        .WithMany("Reviews")
                        .HasForeignKey("TeacherApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.TeacherApplications.TeacherApplicationStatusHistory", b =>
                {
                    b.HasOne("Tafseel.Domain.TeacherApplications.TeacherApplication", null)
                        .WithMany("History")
                        .HasForeignKey("TeacherApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.TeacherApplications.TeacherEvaluationScore", b =>
                {
                    b.HasOne("Tafseel.Domain.TeacherApplications.TeacherApplicationReview", null)
                        .WithMany("Scores")
                        .HasForeignKey("TeacherApplicationReviewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.TeacherApplications.TeacherSubjectQualification", b =>
                {
                    b.HasOne("Tafseel.Domain.Catalog.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("Tafseel.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tafseel.Domain.Catalog.QualificationTopic", b =>
                {
                    b.HasOne("Tafseel.Domain.Catalog.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.Catalog.Topic", b =>
                {
                    b.HasOne("Tafseel.Domain.Catalog.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tafseel.Domain.TeacherApplications.TeacherApplication", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Tafseel.Domain.TeacherApplications.TeacherApplicationReview", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Tafseel.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
