// Arabic exemplar cities from Unicode CLDR; see third-party/UNICODE-LICENSE.txt.
// https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-dates-full/main/ar/timeZoneNames.json
export const AR_ZONE_CITIES: Readonly<Record<string,string>> = {
  "Pacific/Honolulu": "هونولولو",
  "Pacific/Pago_Pago": "باغو باغو",
  "Pacific/Rarotonga": "راروتونغا",
  "Pacific/Easter": "استر",
  "Pacific/Galapagos": "جلاباجوس",
  "Pacific/Fiji": "فيجي",
  "Pacific/Truk": "ترك",
  "Pacific/Ponape": "باناب",
  "Pacific/Kosrae": "كوسرا",
  "Pacific/Guam": "غوام",
  "Pacific/Enderbury": "كانتون",
  "Pacific/Kiritimati": "كيريتي ماتي",
  "Pacific/Tarawa": "تاراوا",
  "Pacific/Kwajalein": "كواجالين",
  "Pacific/Majuro": "ماجورو",
  "Pacific/Saipan": "سايبان",
  "Pacific/Noumea": "نوميا",
  "Pacific/Norfolk": "نورفولك",
  "Pacific/Nauru": "ناورو",
  "Pacific/Niue": "نيوي",
  "Pacific/Chatham": "تشاثام",
  "Pacific/Auckland": "أوكلاند",
  "Pacific/Tahiti": "تاهيتي",
  "Pacific/Marquesas": "ماركيساس",
  "Pacific/Gambier": "جامبير",
  "Pacific/Port_Moresby": "بور مورسبي",
  "Pacific/Bougainville": "بوغانفيل",
  "Pacific/Pitcairn": "بيتكيرن",
  "Pacific/Palau": "بالاو",
  "Pacific/Guadalcanal": "غوادالكانال",
  "Pacific/Fakaofo": "فاكاوفو",
  "Pacific/Tongatapu": "تونغاتابو",
  "Pacific/Funafuti": "فونافوتي",
  "Pacific/Midway": "ميدواي",
  "Pacific/Wake": "واك",
  "Pacific/Efate": "إيفات",
  "Pacific/Wallis": "واليس",
  "Pacific/Apia": "أبيا",
  "Etc/Unknown": "مدينة غير معروفة",
  "Europe/Andorra": "أندورا",
  "Europe/Tirane": "تيرانا",
  "Europe/Vienna": "فيينا",
  "Europe/Mariehamn": "ماريهامن",
  "Europe/Sarajevo": "سراييفو",
  "Europe/Brussels": "بروكسل",
  "Europe/Sofia": "صوفيا",
  "Europe/Minsk": "مينسك",
  "Europe/Zurich": "زيورخ",
  "Europe/Prague": "براغ",
  "Europe/Busingen": "بوسنغن",
  "Europe/Berlin": "برلين",
  "Europe/Copenhagen": "كوبنهاغن",
  "Europe/Tallinn": "تالين",
  "Europe/Madrid": "مدريد",
  "Europe/Helsinki": "هلسنكي",
  "Europe/Paris": "باريس",
  "Europe/London": "لندن",
  "Europe/Guernsey": "غيرنزي",
  "Europe/Gibraltar": "جبل طارق",
  "Europe/Athens": "أثينا",
  "Europe/Zagreb": "زغرب",
  "Europe/Budapest": "بودابست",
  "Europe/Dublin": "دبلن",
  "Europe/Isle_of_Man": "جزيرة مان",
  "Europe/Rome": "روما",
  "Europe/Jersey": "جيرسي",
  "Europe/Vaduz": "فادوز",
  "Europe/Vilnius": "فيلنيوس",
  "Europe/Luxembourg": "لوكسمبورغ",
  "Europe/Riga": "ريغا",
  "Europe/Monaco": "موناكو",
  "Europe/Chisinau": "تشيسيناو",
  "Europe/Podgorica": "بودغوريكا",
  "Europe/Skopje": "سكوبي",
  "Europe/Malta": "مالطة",
  "Europe/Amsterdam": "أمستردام",
  "Europe/Oslo": "أوسلو",
  "Europe/Warsaw": "وارسو",
  "Europe/Lisbon": "لشبونة",
  "Europe/Bucharest": "بوخارست",
  "Europe/Belgrade": "بلغراد",
  "Europe/Kaliningrad": "كالينجراد",
  "Europe/Moscow": "موسكو",
  "Europe/Volgograd": "فولوجراد",
  "Europe/Saratov": "ساراتوف",
  "Europe/Astrakhan": "أستراخان",
  "Europe/Ulyanovsk": "أوليانوفسك",
  "Europe/Kirov": "كيروف",
  "Europe/Samara": "سمراء",
  "Europe/Stockholm": "ستوكهولم",
  "Europe/Ljubljana": "ليوبليانا",
  "Europe/Bratislava": "براتيسلافا",
  "Europe/San_Marino": "سان مارينو",
  "Europe/Istanbul": "إسطنبول",
  "Europe/Kiev": "كييف",
  "Europe/Simferopol": "سيمفروبول",
  "Europe/Vatican": "الفاتيكان",
  "Asia/Dubai": "دبي",
  "Asia/Kabul": "كابول",
  "Asia/Yerevan": "يريفان",
  "Asia/Baku": "باكو",
  "Asia/Dhaka": "دكا",
  "Asia/Bahrain": "البحرين",
  "Asia/Brunei": "بروناي",
  "Asia/Thimphu": "تيمفو",
  "Asia/Urumqi": "أرومكي",
  "Asia/Shanghai": "شنغهاي",
  "Asia/Nicosia": "نيقوسيا",
  "Asia/Famagusta": "فاماغوستا",
  "Asia/Tbilisi": "تبليسي",
  "Asia/Hong_Kong": "هونغ كونغ",
  "Asia/Jakarta": "جاكرتا",
  "Asia/Pontianak": "بونتيانك",
  "Asia/Makassar": "ماكسار",
  "Asia/Jayapura": "جايابيورا",
  "Asia/Jerusalem": "القدس",
  "Asia/Calcutta": "كالكتا",
  "Asia/Baghdad": "بغداد",
  "Asia/Tehran": "طهران",
  "Asia/Amman": "عمّان",
  "Asia/Tokyo": "طوكيو",
  "Asia/Bishkek": "بشكيك",
  "Asia/Phnom_Penh": "بنوم بنه",
  "Asia/Pyongyang": "بيونغ يانغ",
  "Asia/Seoul": "سول",
  "Asia/Kuwait": "الكويت",
  "Asia/Aqtau": "أكتاو",
  "Asia/Oral": "أورال",
  "Asia/Atyrau": "أتيراو",
  "Asia/Aqtobe": "أكتوب",
  "Asia/Qostanay": "قوستاناي",
  "Asia/Qyzylorda": "كيزيلوردا",
  "Asia/Almaty": "ألماتي",
  "Asia/Vientiane": "فيانتيان",
  "Asia/Beirut": "بيروت",
  "Asia/Colombo": "كولومبو",
  "Asia/Rangoon": "رانغون",
  "Asia/Hovd": "هوفد",
  "Asia/Ulaanbaatar": "آلانباتار",
  "Asia/Macau": "ماكاو",
  "Asia/Kuala_Lumpur": "كوالا لامبور",
  "Asia/Kuching": "كيشينج",
  "Asia/Katmandu": "كاتماندو",
  "Asia/Muscat": "مسقط",
  "Asia/Manila": "مانيلا",
  "Asia/Karachi": "كراتشي",
  "Asia/Gaza": "غزة",
  "Asia/Hebron": "هيبرون (مدينة الخليل)",
  "Asia/Qatar": "قطر",
  "Asia/Yekaterinburg": "يكاترنبيرج",
  "Asia/Omsk": "أومسك",
  "Asia/Novosibirsk": "نوفوسبيرسك",
  "Asia/Barnaul": "بارناول",
  "Asia/Tomsk": "تومسك",
  "Asia/Novokuznetsk": "نوفوكوزنتسك",
  "Asia/Krasnoyarsk": "كراسنويارسك",
  "Asia/Irkutsk": "ايركيتسك",
  "Asia/Chita": "تشيتا",
  "Asia/Yakutsk": "ياكتسك",
  "Asia/Vladivostok": "فلاديفوستك",
  "Asia/Khandyga": "خانديجا",
  "Asia/Sakhalin": "سكالين",
  "Asia/Ust-Nera": "أوست نيرا",
  "Asia/Magadan": "مجادن",
  "Asia/Srednekolymsk": "سريدنكوليمسك",
  "Asia/Kamchatka": "كامتشاتكا",
  "Asia/Anadyr": "أندير",
  "Asia/Riyadh": "الرياض",
  "Asia/Singapore": "سنغافورة",
  "Asia/Damascus": "دمشق",
  "Asia/Bangkok": "بانكوك",
  "Asia/Dushanbe": "دوشانبي",
  "Asia/Dili": "ديلي",
  "Asia/Ashgabat": "عشق آباد",
  "Asia/Taipei": "تايبيه",
  "Asia/Samarkand": "سمرقند",
  "Asia/Tashkent": "طشقند",
  "Asia/Saigon": "مدينة هو تشي منة",
  "Asia/Aden": "عدن",
  "America/Antigua": "أنتيغوا",
  "America/Anguilla": "أنغويلا",
  "America/Argentina/Rio_Gallegos": "ريو جالييوس",
  "America/Argentina/San_Juan": "سان خوان",
  "America/Argentina/Ushuaia": "أشوا",
  "America/Argentina/La_Rioja": "لا ريوجا",
  "America/Argentina/San_Luis": "سان لويس",
  "America/Argentina/Salta": "سالطا",
  "America/Argentina/Tucuman": "تاكمان",
  "America/Mendoza": "ميندوزا",
  "America/Catamarca": "كاتاماركا",
  "America/Jujuy": "جوجو",
  "America/Cordoba": "كوردوبا",
  "America/Buenos_Aires": "بوينوس أيرس",
  "America/Aruba": "أروبا",
  "America/Barbados": "بربادوس",
  "America/St_Barthelemy": "سانت بارتيليمي",
  "America/La_Paz": "لا باز",
  "America/Kralendijk": "كرالنديك",
  "America/Eirunepe": "ايرونبي",
  "America/Rio_Branco": "ريوبرانكو",
  "America/Porto_Velho": "بورتو فيلو",
  "America/Boa_Vista": "باو فيستا",
  "America/Manaus": "ماناوس",
  "America/Cuiaba": "كيابا",
  "America/Santarem": "سانتاريم",
  "America/Campo_Grande": "كومبو جراند",
  "America/Belem": "بلم",
  "America/Araguaina": "أروجوانيا",
  "America/Sao_Paulo": "ساو باولو",
  "America/Bahia": "باهيا",
  "America/Fortaleza": "فورتاليزا",
  "America/Maceio": "ماشيو",
  "America/Recife": "ريسيف",
  "America/Noronha": "نوروناه",
  "America/Nassau": "ناسو",
  "America/Belize": "بليز",
  "America/Dawson": "داوسان",
  "America/Whitehorse": "وايت هورس",
  "America/Inuvik": "اينوفيك",
  "America/Vancouver": "فانكوفر",
  "America/Fort_Nelson": "فورت نيلسون",
  "America/Dawson_Creek": "داوسن كريك",
  "America/Creston": "كريستون",
  "America/Edmonton": "ايدمونتون",
  "America/Swift_Current": "سوفت كارنت",
  "America/Cambridge_Bay": "كامبرديج باي",
  "America/Regina": "ريجينا",
  "America/Winnipeg": "وينيبيج",
  "America/Resolute": "ريزولوت",
  "America/Rankin_Inlet": "رانكن انلت",
  "America/Coral_Harbour": "كورال هاربر",
  "America/Toronto": "تورونتو",
  "America/Iqaluit": "اكويلت",
  "America/Moncton": "وينكتون",
  "America/Halifax": "هاليفاكس",
  "America/Goose_Bay": "جوس باي",
  "America/Glace_Bay": "جلاس باي",
  "America/Blanc-Sablon": "بلانك-سابلون",
  "America/St_Johns": "سانت جونس",
  "America/Coyhaique": "كويهايكيو",
  "America/Punta_Arenas": "بونتا أريناز",
  "America/Santiago": "سانتياغو",
  "America/Bogota": "بوغوتا",
  "America/Costa_Rica": "كوستاريكا",
  "America/Havana": "هافانا",
  "America/Curacao": "كوراساو",
  "America/Dominica": "دومينيكا",
  "America/Santo_Domingo": "سانتو دومينغو",
  "America/Guayaquil": "غواياكويل",
  "America/Grenada": "غرينادا",
  "America/Cayenne": "كايين",
  "America/Thule": "ثيل",
  "America/Godthab": "غودثاب",
  "America/Scoresbysund": "سكورسبيسند",
  "America/Danmarkshavn": "دانمرك شافن",
  "America/Guadeloupe": "غوادلوب",
  "America/Guatemala": "غواتيمالا",
  "America/Guyana": "غيانا",
  "America/Tegucigalpa": "تيغوسيغالبا",
  "America/Port-au-Prince": "بورت أو برنس",
  "America/Jamaica": "جامايكا",
  "America/St_Kitts": "سانت كيتس",
  "America/Cayman": "كايمان",
  "America/St_Lucia": "سانت لوشيا",
  "America/Marigot": "ماريغوت",
  "America/Martinique": "المارتينيك",
  "America/Montserrat": "مونتسيرات",
  "America/Tijuana": "تيخوانا",
  "America/Hermosillo": "هيرموسيلو",
  "America/Ciudad_Juarez": "سيوداد خواريز",
  "America/Mazatlan": "مازاتلان",
  "America/Chihuahua": "تشيواوا",
  "America/Bahia_Banderas": "باهيا بانديراس",
  "America/Ojinaga": "أوجيناجا",
  "America/Monterrey": "مونتيري",
  "America/Mexico_City": "مكسيكو سيتي",
  "America/Matamoros": "ماتاموروس",
  "America/Merida": "ميريدا",
  "America/Cancun": "كانكون",
  "America/Managua": "ماناغوا",
  "America/Panama": "بنما",
  "America/Lima": "ليما",
  "America/Miquelon": "مكويلون",
  "America/Puerto_Rico": "بورتوريكو",
  "America/Asuncion": "أسونسيون",
  "America/Paramaribo": "باراماريبو",
  "America/El_Salvador": "السلفادور",
  "America/Lower_Princes": "حي الأمير السفلي",
  "America/Grand_Turk": "غراند ترك",
  "America/Port_of_Spain": "بورت أوف سبين",
  "America/Adak": "أداك",
  "America/Nome": "نوم",
  "America/Anchorage": "أنشوراج",
  "America/Yakutat": "ياكوتات",
  "America/Sitka": "سيتكا",
  "America/Juneau": "جوني",
  "America/Metlakatla": "ميتلاكاتلا",
  "America/Los_Angeles": "لوس انجلوس",
  "America/Boise": "بويس",
  "America/Phoenix": "فينكس",
  "America/Denver": "دنفر",
  "America/North_Dakota/Beulah": "بيولا، داكوتا الشمالية",
  "America/North_Dakota/New_Salem": "نيو ساليم",
  "America/North_Dakota/Center": "سنتر",
  "America/Chicago": "شيكاغو",
  "America/Menominee": "مينوميني",
  "America/Indiana/Vincennes": "فينسينس",
  "America/Indiana/Petersburg": "بيترسبرغ",
  "America/Indiana/Tell_City": "مدينة تل، إنديانا",
  "America/Indiana/Knox": "كونكس",
  "America/Indiana/Winamac": "ويناماك",
  "America/Indiana/Marengo": "مارنجو",
  "America/Indiana/Vevay": "فيفاي",
  "America/Indianapolis": "إنديانابوليس",
  "America/Louisville": "لويس فيل",
  "America/Kentucky/Monticello": "مونتيسيلو",
  "America/Detroit": "ديترويت",
  "America/New_York": "نيويورك",
  "America/Montevideo": "مونتفيديو",
  "America/St_Vincent": "سانت فنسنت",
  "America/Caracas": "كاراكاس",
  "America/Tortola": "تورتولا",
  "America/St_Thomas": "سانت توماس",
  "Africa/Luanda": "لواندا",
  "Africa/Ouagadougou": "واغادوغو",
  "Africa/Bujumbura": "بوجومبورا",
  "Africa/Porto-Novo": "بورتو نوفو",
  "Africa/Gaborone": "غابورون",
  "Africa/Kinshasa": "كينشاسا",
  "Africa/Lubumbashi": "لومبباشا",
  "Africa/Bangui": "بانغوي",
  "Africa/Brazzaville": "برازافيل",
  "Africa/Abidjan": "أبيدجان",
  "Africa/Douala": "دوالا",
  "Africa/Djibouti": "جيبوتي",
  "Africa/Algiers": "الجزائر",
  "Africa/Cairo": "القاهرة",
  "Africa/El_Aaiun": "العيون",
  "Africa/Asmera": "أسمرة",
  "Africa/Ceuta": "سيتا",
  "Africa/Addis_Ababa": "أديس أبابا",
  "Africa/Libreville": "ليبرفيل",
  "Africa/Accra": "أكرا",
  "Africa/Banjul": "بانجول",
  "Africa/Conakry": "كوناكري",
  "Africa/Malabo": "مالابو",
  "Africa/Bissau": "بيساو",
  "Africa/Nairobi": "نيروبي",
  "Africa/Monrovia": "مونروفيا",
  "Africa/Maseru": "ماسيرو",
  "Africa/Tripoli": "طرابلس",
  "Africa/Casablanca": "الدار البيضاء",
  "Africa/Bamako": "باماكو",
  "Africa/Nouakchott": "نواكشوط",
  "Africa/Blantyre": "بلانتاير",
  "Africa/Maputo": "مابوتو",
  "Africa/Windhoek": "ويندهوك",
  "Africa/Niamey": "نيامي",
  "Africa/Lagos": "لاغوس",
  "Africa/Kigali": "كيغالي",
  "Africa/Khartoum": "الخرطوم",
  "Africa/Freetown": "فري تاون",
  "Africa/Dakar": "داكار",
  "Africa/Mogadishu": "مقديشيو",
  "Africa/Juba": "جوبا",
  "Africa/Sao_Tome": "ساو تومي",
  "Africa/Mbabane": "مباباني",
  "Africa/Ndjamena": "نجامينا",
  "Africa/Lome": "لومي",
  "Africa/Tunis": "تونس",
  "Africa/Dar_es_Salaam": "دار السلام",
  "Africa/Kampala": "كامبالا",
  "Africa/Johannesburg": "جوهانسبرغ",
  "Africa/Lusaka": "لوساكا",
  "Africa/Harare": "هراري",
  "Antarctica/Rothera": "روثيرا",
  "Antarctica/Palmer": "بالمير",
  "Antarctica/Troll": "ترول",
  "Antarctica/Syowa": "سايووا",
  "Antarctica/Mawson": "ماوسون",
  "Antarctica/Davis": "دافيز",
  "Antarctica/Vostok": "فوستوك",
  "Antarctica/Casey": "كاساي",
  "Antarctica/DumontDUrville": "دي مونت دو روفيل",
  "Antarctica/McMurdo": "ماك موردو",
  "Antarctica/Macquarie": "ماكواري",
  "Australia/Perth": "برثا",
  "Australia/Eucla": "أوكلا",
  "Australia/Darwin": "دارون",
  "Australia/Adelaide": "أديليد",
  "Australia/Broken_Hill": "بروكن هيل",
  "Australia/Melbourne": "ميلبورن",
  "Australia/Hobart": "هوبارت",
  "Australia/Lindeman": "ليندمان",
  "Australia/Sydney": "سيدني",
  "Australia/Brisbane": "برسيبان",
  "Australia/Lord_Howe": "لورد هاو",
  "Atlantic/Bermuda": "برمودا",
  "Atlantic/Cape_Verde": "الرأس الأخضر",
  "Atlantic/Canary": "كناري",
  "Atlantic/Stanley": "استانلي",
  "Atlantic/Faeroe": "فارو",
  "Atlantic/South_Georgia": "جورجيا الجنوبية",
  "Atlantic/Reykjavik": "ريكيافيك",
  "Atlantic/Azores": "أزورس",
  "Atlantic/Madeira": "ماديرا",
  "Atlantic/St_Helena": "سانت هيلينا",
  "Indian/Cocos": "كوكوس",
  "Indian/Christmas": "كريسماس",
  "Indian/Chagos": "تشاغوس",
  "Indian/Comoro": "جزر القمر",
  "Indian/Antananarivo": "أنتاناناريفو",
  "Indian/Mauritius": "موريشيوس",
  "Indian/Maldives": "المالديف",
  "Indian/Reunion": "ريونيون",
  "Indian/Mahe": "ماهي",
  "Indian/Kerguelen": "كيرغويلين",
  "Indian/Mayotte": "مايوت",
  "Arctic/Longyearbyen": "لونجيربين"
};
